FROM rust:1.75-bookworm AS builder
WORKDIR /build
COPY . .
RUN cargo build --release -p ntpsec-rs-d -p ntpsec-rs-query -p ntpsec-rs-dig

FROM debian:bookworm-slim
RUN apt-get update -qq && apt-get install -y -qq libc6 python3 python3-pip && rm -rf /var/lib/apt/lists/*
COPY --from=builder /build/target/release/ntpd-rs /usr/local/bin/
COPY --from=builder /build/target/release/ntpq-rs /usr/local/bin/
COPY --from=builder /build/target/release/ntpdig-rs /usr/local/bin/
