// ──── ntp_packetstamp.rs ────────────────────────────────────────────────────
// Forensic reconstruction of ntpd/ntp_packetstamp.c
//
// Hardware packet timestamping via SO_TIMESTAMPNS, SO_TIMESTAMPING, and
// ancillary CMSG data parsing.
// =============================================================================

use std::os::unix::io::RawFd;

use crate::ntp_fp;
use crate::ntp_types::NtpTs64;

// ──── Constants from Linux kernel headers ───────────────────────────────────

/// SOF_TIMESTAMPING_RX_HARDWARE — return hardware timestamps of incoming
/// packets.
#[cfg(target_os = "linux")]
const SOF_TIMESTAMPING_RX_HARDWARE: u32 = 1 << 0;

/// SOF_TIMESTAMPING_RX_SOFTWARE — return software timestamps of incoming
/// packets.
#[cfg(target_os = "linux")]
const SOF_TIMESTAMPING_RX_SOFTWARE: u32 = 1 << 3;

/// SOF_TIMESTAMPING_SOFTWARE — return system timestamps generated by
/// software (kernel skb time).
#[cfg(target_os = "linux")]
const SOF_TIMESTAMPING_SOFTWARE: u32 = 1 << 4;

/// SOF_TIMESTAMPING_RAW_HARDWARE — return raw hardware timestamps (not
/// converted to system time).
#[cfg(target_os = "linux")]
const SOF_TIMESTAMPING_RAW_HARDWARE: u32 = 1 << 6;

/// SOF_TIMESTAMPING_OPT_ID — include the ID field in the timestamp report.
#[cfg(target_os = "linux")]
const _SOF_TIMESTAMPING_OPT_ID: u32 = 1 << 7;

/// SOF_TIMESTAMPING_OPT_CMSG — pass timestamp reports as cmsg data alongside
/// the packet, rather than requiring a separate `recvmsg()` call.
#[cfg(target_os = "linux")]
const _SOF_TIMESTAMPING_OPT_CMSG: u32 = 1 << 10;

// ──── Timestamping Modes ────────────────────────────────────────────────────

/// Timestamping modes supported.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TimestampMode {
    /// Software timestamps via SO_TIMESTAMPNS (reliable, widely supported).
    Software,
    /// Hardware timestamps via SO_TIMESTAMPING (requires NIC support).
    Hardware,
    /// No timestamping (use system clock at recvfrom time).
    None,
}

// ──── Socket Option Helpers ─────────────────────────────────────────────────

/// Enable software receive timestamps on a socket.
///
/// This enables `SO_TIMESTAMPNS` which provides nanosecond-precision receive
/// timestamps generated by the kernel at the moment the packet is received by
/// the network stack.  The timestamp is delivered as a `timespec` in the
/// `SCM_TIMESTAMPNS` ancillary data message.
pub fn enable_software_timestamps(fd: RawFd) -> Result<(), String> {
    let on: libc::c_int = 1;
    let rc = unsafe {
        libc::setsockopt(
            fd,
            libc::SOL_SOCKET,
            libc::SO_TIMESTAMPNS,
            &on as *const _ as *const libc::c_void,
            std::mem::size_of::<libc::c_int>() as libc::socklen_t,
        )
    };
    if rc == 0 {
        Ok(())
    } else {
        Err(format!(
            "SO_TIMESTAMPNS failed: {}",
            std::io::Error::last_os_error()
        ))
    }
}

/// Enable hardware receive timestamps on a socket.
///
/// This enables `SO_TIMESTAMPING` with `SOF_TIMESTAMPING_RX_HARDWARE`,
/// `SOF_TIMESTAMPING_RX_SOFTWARE` (fallback), and `SOF_TIMESTAMPING_SOFTWARE`
/// flags.  The timestamp is delivered as an array of `timespec` values in the
/// `SCM_TIMESTAMPING` ancillary data message.
///
/// Hardware timestamping requires NIC and driver support (e.g. Intel igb/ixgbe,
/// Solarflare sfc, etc.).  When unavailable, the call succeeds but only
/// software timestamps will be returned.
#[cfg(target_os = "linux")]
pub fn enable_hardware_timestamps(fd: RawFd) -> Result<(), String> {
    let flags: u32 = SOF_TIMESTAMPING_RX_HARDWARE
        | SOF_TIMESTAMPING_RX_SOFTWARE
        | SOF_TIMESTAMPING_SOFTWARE
        | SOF_TIMESTAMPING_RAW_HARDWARE;

    let rc = unsafe {
        libc::setsockopt(
            fd,
            libc::SOL_SOCKET,
            libc::SO_TIMESTAMPING,
            &flags as *const _ as *const libc::c_void,
            std::mem::size_of::<u32>() as libc::socklen_t,
        )
    };
    if rc == 0 {
        Ok(())
    } else {
        Err(format!(
            "SO_TIMESTAMPING failed: {}",
            std::io::Error::last_os_error()
        ))
    }
}

/// Stub for non-Linux platforms.
#[cfg(not(target_os = "linux"))]
pub fn enable_hardware_timestamps(_fd: RawFd) -> Result<(), String> {
    Err("hardware timestamping requires Linux SO_TIMESTAMPING".to_string())
}

/// Enable or disable receiving the packet info (destination address) via
/// `IP_PKTINFO` / `IPV6_PKTINFO`.  This is often paired with timestamping so
/// the receiver can determine which local address the packet arrived on.
pub fn enable_pktinfo(fd: RawFd, is_ipv6: bool) -> Result<(), String> {
    let on: libc::c_int = 1;
    let level = if is_ipv6 {
        libc::IPPROTO_IPV6
    } else {
        libc::IPPROTO_IP
    };
    let opt = if is_ipv6 {
        libc::IPV6_PKTINFO
    } else {
        libc::IP_PKTINFO
    };
    let rc = unsafe {
        libc::setsockopt(
            fd,
            level,
            opt,
            &on as *const _ as *const libc::c_void,
            std::mem::size_of::<libc::c_int>() as libc::socklen_t,
        )
    };
    if rc == 0 {
        Ok(())
    } else {
        Err(format!(
            "PKTINFO failed: {}",
            std::io::Error::last_os_error()
        ))
    }
}

// ──── Timestamp Extraction from Ancillary Data ─────────────────────────────

/// The type of timestamp extracted from CMSG ancillary data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TimestampType {
    /// Software timestamp via `SO_TIMESTAMPNS` (`SCM_TIMESTAMPNS`).
    Software,
    /// Hardware timestamp via `SO_TIMESTAMPING` (`SCM_TIMESTAMPING`).
    ///
    /// The contained `bool` indicates whether the timestamp is a raw hardware
    /// timestamp (`true`) or a software fallback (`false`).
    Hardware(bool),
    /// Fallback timestamp generated at the time of the `recvmsg()` call.
    Fallback,
}

/// A received packet timestamp with its type metadata.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PacketTimestamp {
    /// The timestamp in NTP 64-bit fixed-point format.
    pub ntp_time: NtpTs64,
    /// The origin of the timestamp (software, hardware, or fallback).
    pub source: TimestampType,
}

/// Parse ancillary data (CMSG) for receive timestamps.
///
/// After a `recvmsg()` call, the `msg_control` buffer may contain timestamp
/// information in the following ancillary data records:
///
/// | Level       | Type              | Data                          |
/// |-------------|-------------------|-------------------------------|
/// | SOL_SOCKET  | SCM_TIMESTAMPNS   | `struct timespec`             |
/// | SOL_SOCKET  | SCM_TIMESTAMPING  | `struct timespec[3]`          |
///
/// For `SCM_TIMESTAMPING`, the three `timespec` entries are:
///   0. Hardware timestamp
///   1. Software timestamp (converted from hardware)
///   2. Software timestamp (kernel skb time)
///
/// This function iterates the CMSG list and returns the best available
/// timestamp: hardware preferred, then software, then `None`.
///
/// # Arguments
///
/// * `msg_control` — The raw `cmsg_buffer` from `recvmsg()`.
/// * `msg_controllen` — The length of the control buffer.
pub fn recv_timestamp_from_cmsg(
    msg_control: &[u8],
    msg_controllen: usize,
) -> Option<PacketTimestamp> {
    // The msg_controllen we get back from recvmsg() may be less than the
    // allocated buffer.  Use only the actual length.
    let control_len = msg_controllen.min(msg_control.len());
    if control_len < std::mem::size_of::<libc::cmsghdr>() {
        return None;
    }

    let mut best: Option<PacketTimestamp> = None;

    // Walk the CMSG chain.
    // CMSG_NXTHDR is safe here because we pass the aligned cmsghdr pointer
    // and the actual data length returned by recvmsg().
    let cmsg_data = &msg_control[..control_len];

    // We need a *mut cmsghdr to iterate; we construct a pointer to the start
    // of the control buffer. This is safe because we only read CMSG fields,
    // and recvmsg() populated the buffer.
    let cmsg_hdr_ptr = cmsg_data.as_ptr() as *const libc::cmsghdr;
    // Align: cmsg_hdr_ptr must satisfy CMSG alignment. It comes from the
    // kernel via recvmsg(), so it is always properly aligned.

    let mut current: *const libc::cmsghdr = cmsg_hdr_ptr;

    // Safety: We traverse the cmsghdr chain using CMSG_NXTHDR semantics.
    // The data was written by the kernel via recvmsg() and is guaranteed to
    // be valid as long as msg_controllen is correct.
    loop {
        if current.is_null() {
            break;
        }

        // Read cmsg_len; the kernel writes it, so it's safe.
        let cmsg_len;
        let cmsg_level;
        let cmsg_type;
        unsafe {
            cmsg_len = (*current).cmsg_len;
            cmsg_level = (*current).cmsg_level;
            cmsg_type = (*current).cmsg_type;
        }

        // Ensure the reported length is within our buffer.
        if (cmsg_len as usize) < std::mem::size_of::<libc::cmsghdr>() {
            break;
        }

        // Compute the offset of this cmsghdr from the start.
        let offset = (current as usize) - (cmsg_hdr_ptr as usize);
        let data_offset = offset + aligned_cmsg_data_offset();
        let data_len = (cmsg_len as usize).saturating_sub(std::mem::size_of::<libc::cmsghdr>());

        if cmsg_level == libc::SOL_SOCKET && cmsg_type == libc::SCM_TIMESTAMPNS as libc::c_int {
            // SCM_TIMESTAMPNS: data is a single struct timespec.
            if data_len >= std::mem::size_of::<libc::timespec>() {
                let ts: &libc::timespec =
                    unsafe { &*(cmsg_data.as_ptr().add(data_offset) as *const libc::timespec) };
                let ntp_time = timespec_to_ntp(ts);
                best = Some(PacketTimestamp {
                    ntp_time,
                    source: TimestampType::Software,
                });
            }
        } else if cmsg_level == libc::SOL_SOCKET
            && (cmsg_type as libc::c_int) == scm_timestamping_cmsg_type()
        {
            // SCM_TIMESTAMPING: data is three struct timespec values.
            // [0] = hardware timestamp (best)
            // [1] = software converted timestamp
            // [2] = software skb timestamp
            if data_len >= 3 * std::mem::size_of::<libc::timespec>() {
                let ts_array: &[libc::timespec] = unsafe {
                    std::slice::from_raw_parts(
                        cmsg_data.as_ptr().add(data_offset) as *const libc::timespec,
                        3,
                    )
                };

                // Prefer the hardware timestamp (index 0).
                let (ts, is_hardware) = if ts_array[0].tv_sec != 0 || ts_array[0].tv_nsec != 0 {
                    (&ts_array[0], true)
                } else if ts_array[1].tv_sec != 0 || ts_array[1].tv_nsec != 0 {
                    (&ts_array[1], false)
                } else {
                    (&ts_array[2], false)
                };

                let ntp_time = timespec_to_ntp(ts);
                best = Some(PacketTimestamp {
                    ntp_time,
                    source: TimestampType::Hardware(is_hardware),
                });
            }
        }

        // Advance to the next cmsghdr.
        // CMSG_NXTHDR: align cmsg_len to sizeof(cmsghdr), add to pointer.
        let next_offset = align_cmsg_len(cmsg_len as usize);

        if next_offset < std::mem::size_of::<libc::cmsghdr>() {
            break;
        }

        let next_ptr = unsafe { (current as *const u8).add(next_offset) as *const libc::cmsghdr };
        let next_offset_from_start = (next_ptr as usize) - (cmsg_hdr_ptr as usize);

        if next_offset_from_start + std::mem::size_of::<libc::cmsghdr>() > control_len {
            break;
        }

        if next_offset_from_start >= control_len {
            break;
        }

        current = next_ptr;
    }

    best
}

// ──── The NTP Packet Stamp Type ─────────────────────────────────────────────

/// The NTP timestamping namespace.
///
/// In production, timestamps from `recvmsg()` ancillary data are read here
/// and stored for the caller.  The `PacketStamp` is produced for each
/// received packet, carrying both the packet data and its receive timestamp.
#[derive(Debug, Clone)]
pub struct PacketStamp {
    /// The best available receive timestamp.
    pub timestamp: Option<PacketTimestamp>,
    /// The mode of timestamping that was active for this receive.
    pub mode: TimestampMode,
}

impl PacketStamp {
    /// Create a new `PacketStamp` with no timestamp (timestamping disabled).
    pub fn new() -> Self {
        Self {
            timestamp: None,
            mode: TimestampMode::None,
        }
    }

    /// Create a `PacketStamp` for a socket configured with the given mode.
    ///
    /// After receiving a packet with `recvmsg()`, call [`PacketStamp::from_cmsg`]
    /// to populate the timestamp from ancillary data.
    pub fn with_mode(mode: TimestampMode) -> Self {
        Self {
            timestamp: None,
            mode,
        }
    }

    /// Extract the timestamp from the `recvmsg()` ancillary data buffer.
    ///
    /// This should be called after every `recvmsg()` with the contents of
    /// `msg_control` and `msg_controllen` as returned by the kernel.
    ///
    /// Returns a reference to self for chaining.
    pub fn from_cmsg(&mut self, msg_control: &[u8], msg_controllen: usize) -> &mut Self {
        self.timestamp = recv_timestamp_from_cmsg(msg_control, msg_controllen);
        self
    }

    /// Clear the stored timestamp.
    pub fn clear(&mut self) {
        self.timestamp = None;
    }

    /// Whether a timestamp was successfully extracted.
    pub fn has_timestamp(&self) -> bool {
        self.timestamp.is_some()
    }

    /// The NTP 64-bit timestamp value, if available.
    pub fn ntp_ts(&self) -> Option<NtpTs64> {
        self.timestamp.map(|pt| pt.ntp_time)
    }
}

impl Default for PacketStamp {
    fn default() -> Self {
        Self::new()
    }
}

// ──── Internal Helpers ──────────────────────────────────────────────────────

/// Convert a `libc::timespec` to an NTP 64-bit fixed-point timestamp.
fn timespec_to_ntp(ts: &libc::timespec) -> NtpTs64 {
    ntp_fp::ts_to_ntp(ts.tv_sec, ts.tv_nsec as i64)
}

/// Return the offset from the start of a `cmsghdr` struct to its data.
/// This accounts for any trailing padding in the `cmsghdr` on the platform.
fn aligned_cmsg_data_offset() -> usize {
    // CMSG_DATA(cmsg) = (unsigned char *)(cmsg) + _CMSG_ALIGN(sizeof(struct cmsghdr))
    align_cmsg_len(std::mem::size_of::<libc::cmsghdr>())
}

/// Align a length to the CMSG alignment boundary (typically pointer-size).
fn align_cmsg_len(len: usize) -> usize {
    #[cfg(target_os = "linux")]
    const CMSG_ALIGNTO: usize = std::mem::size_of::<usize>();
    #[cfg(not(target_os = "linux"))]
    const CMSG_ALIGNTO: usize = std::mem::size_of::<u32>();

    (len + CMSG_ALIGNTO - 1) & !(CMSG_ALIGNTO - 1)
}

/// Return the CMSG type constant for SCM_TIMESTAMPING.
///
/// On Linux this is `SOF_TIMESTAMPING_MSG_ID` / `SCM_TIMESTAMPING` (0x2C as
/// defined in Linux `socket.h`).  On other platforms this may differ.
#[cfg(target_os = "linux")]
fn scm_timestamping_cmsg_type() -> libc::c_int {
    // SCM_TIMESTAMPING is defined as SOF_TIMESTAMPING_MSG_ID = 0x2C in
    // Linux include/uapi/asm-generic/socket.h on newer kernels.
    // libc::SCM_TIMESTAMPING may not be available in all libc versions.
    const SCM_TIMESTAMPING_LINUX: libc::c_int = 0x2C;
    // Prefer the libc constant if available, fall back to the literal.
    let _ = libc::SCM_TIMESTAMPING;
    SCM_TIMESTAMPING_LINUX
}

#[cfg(not(target_os = "linux"))]
fn scm_timestamping_cmsg_type() -> libc::c_int {
    // On non-Linux, just use a placeholder. Hardware timestamping is Linux-only.
    0
}

// ──── Tests ─────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_enable_software_timestamps_invalid_fd() {
        // An invalid file descriptor should produce an error.
        let result = enable_software_timestamps(-1);
        assert!(result.is_err());
    }

    #[test]
    fn test_enable_hardware_timestamps_invalid_fd() {
        let result = enable_hardware_timestamps(-1);
        // On non-Linux, this returns an error immediately. On Linux with an
        // invalid fd, setsockopt returns EBADF. Either way, expect an error.
        assert!(result.is_err());
    }

    #[test]
    fn test_enable_pktinfo_invalid_fd() {
        let result = enable_pktinfo(-1, false);
        assert!(result.is_err());
    }

    #[test]
    fn test_align_cmsg_len() {
        // Alignment rounds up to pointer-size boundary.
        let align = std::mem::size_of::<usize>();
        assert_eq!(align_cmsg_len(0), 0);
        assert_eq!(align_cmsg_len(1), align);
        assert_eq!(align_cmsg_len(align), align);
        assert_eq!(align_cmsg_len(align + 1), 2 * align);
    }

    #[test]
    fn test_timespec_to_ntp_epoch() {
        let ts = libc::timespec {
            tv_sec: 0,
            tv_nsec: 0,
        };
        let ntp = timespec_to_ntp(&ts);
        // Unix epoch 1970-01-01 maps to NTP era 0, offset NTP_EPOCH_OFFSET.
        assert_eq!(ntp.seconds, ntp_fp::NTP_TO_UNIX_OFFSET as i64);
        assert_eq!(ntp.fraction, 0);
    }

    #[test]
    fn test_timespec_to_ntp_modern() {
        let ts = libc::timespec {
            tv_sec: 1_700_000_000,
            tv_nsec: 500_000_000, // 0.5 sec
        };
        let ntp = timespec_to_ntp(&ts);
        // NTP seconds = Unix seconds + NTP_TO_UNIX_OFFSET
        let expected_secs = 1_700_000_000i64 + ntp_fp::NTP_TO_UNIX_OFFSET as i64;
        assert_eq!(ntp.seconds, expected_secs);
        // 0.5 sec in NTP fraction = 2^31 (half of 2^32)
        assert_eq!(ntp.fraction, (1u64 << 31) as u32);
    }

    #[test]
    fn test_packet_stamp_default() {
        let stamp = PacketStamp::new();
        assert!(stamp.timestamp.is_none());
        assert_eq!(stamp.mode, TimestampMode::None);
    }

    #[test]
    fn test_packet_stamp_with_mode() {
        let stamp = PacketStamp::with_mode(TimestampMode::Software);
        assert!(stamp.timestamp.is_none());
        assert_eq!(stamp.mode, TimestampMode::Software);
    }

    #[test]
    fn test_packet_stamp_clear() {
        let mut stamp = PacketStamp::with_mode(TimestampMode::Software);
        // Simulate a timestamp by setting it directly.
        stamp.timestamp = Some(PacketTimestamp {
            ntp_time: NtpTs64 {
                seconds: 0,
                fraction: 0,
            },
            source: TimestampType::Software,
        });
        assert!(stamp.has_timestamp());
        stamp.clear();
        assert!(!stamp.has_timestamp());
    }

    #[test]
    fn test_recv_timestamp_empty_buffer() {
        // An empty or too-small CMSG buffer should return None.
        let result = recv_timestamp_from_cmsg(&[], 0);
        assert!(result.is_none());
    }

    #[test]
    fn test_timestamp_type_debug() {
        let hw = TimestampType::Hardware(true);
        let sw = TimestampType::Software;
        assert_eq!(format!("{hw:?}"), "Hardware(true)");
        assert_eq!(format!("{sw:?}"), "Software");
    }

    #[test]
    fn test_packet_timestamp_equality() {
        let ts1 = PacketTimestamp {
            ntp_time: NtpTs64 {
                seconds: 100,
                fraction: 200,
            },
            source: TimestampType::Software,
        };
        let ts2 = PacketTimestamp {
            ntp_time: NtpTs64 {
                seconds: 100,
                fraction: 200,
            },
            source: TimestampType::Software,
        };
        assert_eq!(ts1, ts2);
    }
}
