// ──── ntpkeygen-rs — NTP key generator ──────────────────────────────────────
//
// Forensic Rust reconstruction of ntpkeygen.
//
// # Usage
//
//   ntpkeygen-rs                    # generate default keys
//   ntpkeygen-rs -o /etc/ntp.keys   # specify output file
//   ntpkeygen-rs -n 10              # generate 10 keys
//
// ## Oracle
//   - ntpsec ntpclients/ntpkeygen.py (4K)
// =============================================================================

use std::io::Write;

use clap::Parser;

/// NTP key generator — forensic Rust reconstruction of ntpkeygen.
#[derive(Parser, Debug)]
#[command(name = "ntpkeygen-rs", about = "NTP key generator", version)]
struct Cli {
    /// Output file path
    #[arg(short = 'o', long, default_value = "/etc/ntp.keys")]
    output: String,

    /// Number of keys to generate
    #[arg(short = 'n', long, default_value = "10")]
    count: u32,

    /// Digest type: MD5, SHA1, SHA256, AES-128-CMAC
    #[arg(short = 'd', long, default_value = "MD5")]
    digest: String,

    /// Key length in bytes
    #[arg(short = 'l', long, default_value = "16")]
    key_length: u32,

    /// Print keys to stdout instead of writing to file
    #[arg(short = 'p', long)]
    print: bool,
}

fn generate_key(length: u32) -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let seed = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let mut key = String::with_capacity(length as usize * 2);
    let mut rng = seed;
    for _ in 0..length {
        rng = rng
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        let byte = ((rng >> 32) & 0xFF) as u8;
        // Use only hex chars for readability
        let idx = (byte % 16) as usize;
        key.push("0123456789abcdef".as_bytes()[idx] as char);
    }
    key
}

fn main() -> std::io::Result<()> {
    let cli = Cli::parse();

    let digest = cli.digest.to_uppercase();
    let valid_digests = ["MD5", "SHA1", "SHA256", "AES-128-CMAC"];
    if !valid_digests.contains(&digest.as_str()) {
        eprintln!("Warning: unknown digest type '{}', using MD5", cli.digest);
    }

    // Generate key entries
    let mut output = String::new();
    output.push_str(&format!("# NTP keys generated by ntpkeygen-rs\n"));
    output.push_str(&format!(
        "# Digest: {}, key length: {} bytes\n",
        digest, cli.key_length
    ));
    output.push_str(&format!(
        "# Generated: {}\n\n",
        chrono_now().unwrap_or_else(|| "unknown".to_string())
    ));

    for i in 1..=cli.count {
        let key = generate_key(cli.key_length);
        output.push_str(&format!("{} {} {}\n", i, digest, key));
    }

    if cli.print {
        print!("{}", output);
    } else {
        // Write to file
        let path = &cli.output;
        if path == "/dev/stdout" {
            print!("{}", output);
        } else {
            // Create parent directories if needed
            if let Some(parent) = std::path::Path::new(path).parent() {
                let _ = std::fs::create_dir_all(parent);
            }
            let mut file = std::fs::File::create(path)?;
            file.write_all(output.as_bytes())?;
            println!("Wrote {} keys to {}", cli.count, path);
        }
    }

    Ok(())
}

fn chrono_now() -> Option<String> {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()?;
    let secs = now.as_secs() as i64;
    let ut = unsafe { libc::localtime(&secs) };
    if ut.is_null() {
        return None;
    }
    let tm = unsafe { *ut };
    Some(format!(
        "{:04}-{:02}-{:02} {:02}:{:02}:{:02}",
        tm.tm_year + 1900,
        tm.tm_mon + 1,
        tm.tm_mday,
        tm.tm_hour,
        tm.tm_min,
        tm.tm_sec,
    ))
}
